### ISSUE TITLE
Unexpectedly found nil while unwrapping an optional value if using cocoa pods

### ISSUE THREAD

**Issue by AlexChesters** [gilesvangruisen/Swift-YouTube-Player#24]
In this function
```swift
private func playerHTMLPath() -> String {
        return NSBundle(forClass: self.classForCoder).pathForResource("YTPlayer", ofType: "html")!
}
```

**Comment by memetcircus** [comment]
I have ran into the same error. Also Pods_YouTubeVideoPlayer.framework and YouTubePlayer.framework is all red in the navigator.

**Comment by AlexChesters** [comment]
Ditto @memetcircus, do you know of any solution/workaround?

**Comment by memetcircus** [comment]
Couldn't find any but it seems that it happens if I use cocoa pods

**Comment by AlexChesters** [comment]
@memetcircus how do you use it without Cocoa Pods?

**Comment by AlexChesters** [comment]
Same, it looks like the YTPlayer.html is missing

**Comment by memetcircus** [comment]
@AlexChesters checkout my fork at my page. I fixed the bug.

**Comment by DantePuglisi** [comment]
I'm having the same issue but when using `videoPlayer.loadVideoURL(url)` (also tried with your fork @memetcircus with no luck)

**Comment by memetcircus** [comment]
Did you install cocoa pods on your machine ?

--  
Mehmet Akif
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by Jalsemgeest** [comment]
I'm having this same issue.  Any word on a fix?  I tried manually changing the file that @memetcircus had changed, however it didn't seem to fix the issue.

**Comment by AlexChesters** [comment]
@Jalsemgeest it works perfectly if you don't use cocoapods, only workaround I've found

**Comment by DantePuglisi** [comment]
Add YTPlayer.html manually to your project's resources, then change the line I wrote above or fork my version of the project in cocoapods.

**Comment by gilesvangruisen** [comment]
Hey @memetcircus. Do you think you could open a pull request between your fork and the `master` branch? Thanks!

**Comment by mohanmoorthy** [comment]
If your'e using cocoa pods you will definitely get error. To resolve this issue I copied the "YTPlayer.html" file into MY PROJECT (not YouTubePlayer) supporting files folder and checnge the below code in Pods/YouTubePlayer/YouTubePlayer.swift 

private func playerHTMLPath() -> String {
       // return NSBundle(forClass: self.classForCoder).pathForResource("YTPlayer", ofType: "html")!
        return NSBundle.mainBundle().pathForResource("YTPlayer", ofType: "html")!
    }

**Comment by MattxDamon** [comment]
@mohanmoorthy thanks man!
